src/LocalDateRange.php, tests/LocalDateRangeTest.php
New methods
- LocalDateRange::isIntersect() returns whether this LocalDateRange intersect with the given date range.
- LocalDateRange::getIntersection() returns intersection this LocalDateRange with the given date range, exception if ranges do not intersect
=> Add LocalDateRange::isIntersect method

.travis.yml, composer.json, psalm.xml, src/DefaultClock.php, src/Duration.php, src/Instant.php, src/LocalDateRange.php, src/TimeZoneRegion.php, src/YearMonthRange.php, src/ZonedDateTime.php
This is using the second strictest set of checks in Psalm default
configs. It might be interesting to get the library working on
the strictest level, which would mean resolving all the issues with
mixed types
=> Add static analysis using Psalm, and fix reported issues

src/LocalDateRange.php, tests/LocalDateRangeTest.php
Adds a `toDatePeriod` to the `LocalDateRange` object which returns a native \DatePeriod PHP object. 
I opted to do end of day (instead of midnight next day) to be inline with the inclusive nature of LocalDateRange.
Note: This is not `bricks/date-time` Period class - I hope this doesn't create confusion.
=> add toDatePeriod method for LocalDateRange

src/TimeZoneRegion.php
`TimeZoneRegion::parse(...)` should return `TimeZoneRegion` and not `TimeZone`, matching the return type of the proxied `from(...)` method.
=> Fix return type of TimeZoneRegion::parse()

src/Year.php, src/YearMonth.php, src/YearMonthRange.php, src/YearWeek.php, tests/YearMonthRangeTest.php, tests/YearMonthTest.php, tests/YearTest.php, tests/YearWeekTest.php
New methods:
- `Year::toLocalDateRange`
- `YearMonth::toLocalDateRange`
- `YearMonthRange::toLocalDateRange`
- `YearWeek::toLocalDateRange`
=> New toLocalDateRange method in Year, YearMonth, YearMonthRange and YearWeek classes

src/Interval.php, tests/IntervalTest.php
=> Implement contains, intersection and `of` methods for Interval

src/DateTimeException.php, src/Field/TimeZoneOffsetSecond.php, src/Field/TimeZoneOffsetTotalSeconds.php, src/Parser/IsoParsers.php, src/TimeZone.php, src/TimeZoneOffset.php, tests/TimeZoneOffsetTest.php, tests/TimeZoneTest.php, tests/ZonedDateTimeTest.php
=> Bring back support for sub-minute offsets in PHP >= 8.1.7

src/ZonedDateTime.php, tests/ZonedDateTimeTest.php
Just more convenient way to get Duration between two ZonedDateTime
```php
$duration = Duration::between($first->getInstant(), $second->getInstant());
->
$duration = $first->getDurationTo($second);
```
=> Add ZonedDateTime::getDurationTo method

src/LocalDate.php, src/LocalDateTime.php, src/LocalTime.php
Hello there,
We're using this library quite extensively in our codebase, and often happen to call methods **a lot** (like 4 million times in a request), which allows us to witness a few performance bottlenecks. So here's a very simple one we thought we could address.
Creating a new instance of LocalDate/LocalDateTime/LocalTime using the min() and max() functions is unnecessary, and we can achieve the same behavior by using array_shift (extracting the first element of the array to have a reference point for further comparisons). And we don't need to take care of the "empty array" scenario, as there's already a condition above it that throws an Exception. Finally, cherry-on-the-cake, it makes one less loop iteration.
Credit goes to [@BastienClement](https://github.com/BastienClement).
=> [performance] Optimize minOf/maxOf methods.

src/Duration.php, src/Instant.php, src/LocalDate.php, src/LocalDateTime.php, src/LocalTime.php, src/Period.php, src/TimeZoneOffset.php, tests/DurationTest.php, tests/InstantTest.php, tests/LocalDateTest.php, tests/LocalDateTimeTest.php, tests/LocalTimeTest.php, tests/PeriodTest.php, tests/TimeZoneOffsetTest.php, tests/TimeZoneTest.php
Hello folks,
Here's another performance optimization when static constructors are called a lot. It was already done for some methods in the library, so I kept the same code style and applied it to all static constructors that take no arguments ("constants", in a way).
Let me know if you think some of these do not deserve it. I applied it everywhere without much thinking about it, because I don't think there's any downside of having that static variable, and I definitely know that some of these methods show up a lot in our benchmarks, like `TimeZone(Offset)::utc()` and `Duration::zero()`, `min()/max()`, etc, and then it's definitely beneficial.
=> [performance] Use static variables inside every singleton constructors.

tests/AbstractTestCase.php, tests/Clock/FixedClockTest.php, tests/Clock/OffsetClockTest.php, tests/Clock/ScaleClockTest.php, tests/Clock/SystemClockTest.php, tests/DayOfWeekTest.php, tests/DefaultClockTest.php, tests/DurationTest.php, tests/InstantTest.php, tests/IntervalTest.php, tests/LocalDateRangeTest.php, tests/LocalDateTest.php, tests/LocalDateTimeTest.php, tests/LocalTimeTest.php, tests/MonthDayTest.php, tests/MonthTest.php, tests/PeriodTest.php, tests/StopwatchTest.php, tests/TimeZoneOffsetTest.php, tests/TimeZoneRegionTest.php, tests/TimeZoneTest.php, tests/Utility/MathTest.php, tests/YearMonthRangeTest.php, tests/YearMonthTest.php, tests/YearTest.php, tests/YearWeekTest.php, tests/ZonedDateTimeTest.php, tools/ecs/ecs.php
This is for preference.
Related to https://github.com/brick/date-time/pull/77#issuecomment-1721904161
Note that custom `assertX` functions are not supported by the fixer, it only take into account PHPUnit ones.
I had to manually replace them to maintain consistency.
=> Call PHPUnit methods through `self::` instead of `$this->`

src/Instant.php, src/ZonedDateTime.php, tests/InstantTest.php, tests/ZonedDateTimeTest.php
More convenient way to get Interval from two ZonedDateTime.
```php
$a->getIntervalTo($b);
// vs old version
Interval::of($a->getInstant(), $b->getInstant())
```
relates to https://github.com/brick/date-time/pull/71
=> ZonedDateTime::getIntervalTo and Instant::getIntervalTo

src/Field/WeekOfYear.php, src/Parser/IsoParsers.php, src/Year.php, src/YearWeek.php, tests/YearTest.php, tests/YearWeekTest.php
Fixes #68 by adding : 
* `YearWeek::parse('2023-W39');`
* `Year::parse('2023');`
*  ~`DayOfWeek::parse('06');`~
* ~`Month::parse('October');`~
I was not sure it made sense to add `Year::parse()`, because it's so close to `Year::of((int) $string)`. But then I realized they do differ for dates (positive and negative) under 1000 / 100 / 10 because of the trailing zeroes : 
```php
Year::of((int) '-100'); // works
Year::of((int) '-0100'); // works, interpreted as -100 (PHP, right? :>)
Year::parse('-100'); // should throw an Exception, as the valid ISO is "-0100"
Year::parse('-0100'); // works
```
~Same for `DayOfWeek` with its leading zero. I know `DayOfMonth` and `Month` will be converted into Enums in the next version ([0.6](https://github.com/brick/date-time/tree/v0.6?rgh-link-date=2023-09-1 …
=> Add parsing methods where missing.

src/Year.php, tests/YearTest.php
=> Stringify years correctly according to ISO 8601

src/Year.php, tests/YearTest.php
=> Year::atMonth(): deprecate int argument, add support for Month enum.

src/DayOfWeek.php, src/Duration.php, src/Instant.php, src/Interval.php, src/LocalDate.php, src/LocalDateRange.php, src/LocalDateTime.php, src/LocalTime.php, src/Month.php, src/MonthDay.php, src/Period.php, src/TimeZone.php, src/Year.php, src/YearMonth.php, src/YearMonthRange.php, src/YearWeek.php, src/ZonedDateTime.php
Below are the two types improvements I've noticed were missing when we've integrated the library in our application. I've not read every code signature to make sure everything was as precise as it could be though, so maybe other type improvements will come in the future.
=> Add @psalm-* annotations for better static analysis (compatible with PHPStan too)

.gitignore, src/Clock/FixedClock.php, src/Clock/OffsetClock.php, src/Clock/ScaleClock.php, src/Duration.php, src/Instant.php, src/Interval.php, src/LocalDate.php, src/LocalDateRange.php, src/LocalDateTime.php, src/LocalTime.php, src/MonthDay.php, src/Parser/PatternParser.php, src/Period.php, src/TimeZoneOffset.php, src/TimeZoneRegion.php, src/Year.php, src/YearMonth.php, src/YearMonthRange.php, src/YearWeek.php, src/ZonedDateTime.php, tests/AbstractTestCase.php, tests/InstantTest.php, tests/IntervalTest.php, tests/LocalDateRangeTest.php, tests/YearMonthRangeTest.php, tools/ecs/ecs.php, tools/rector/composer.json, tools/rector/rector.php
Hello there! I've noticed that the project was not using promoted properties, even though its minimum PHP version supports them. Yet it's using readonly properties already. So I thought it would be a good idea to add Rector in the project to allow doing automated refactorings to keep the codebase up-to-date.
With the current config file, if you bump the minimum PHP version in `composer.json`, it will apply the refactorings that can be done in the new PHP version, making sure the code is always the latest and brightest.
cf. https://getrector.com/documentation/integration-to-new-project
Let me know what you think.
=> Install Rector and apply ClassPropertyAssignToConstructorPromotionRector

src/Field/WeekOfYear.php, src/LocalDate.php, src/LocalDateTime.php, src/LocalTime.php, src/MonthDay.php, src/Year.php, src/YearWeek.php, src/ZonedDateTime.php, tests/LocalDateTest.php, tests/LocalDateTimeTest.php, tests/MonthDayTest.php, tests/ZonedDateTimeTest.php
Covers : 
* `MonthDay::of()` + `MonthDay::withMonth()`
* `LocalDate::of()` + `LocalDate::withMonth()`
* `LocalDateTime::of()` + `LocalDateTime::withMonth()`
* `ZonedDateTime::withMonth()`
And some code clean-up.
=> Allows Month enum everywhere

src/ZonedDateTime.php
=> Fix a typo in ZonedDateTime

src/Stopwatch.php, tests/StopwatchTest.php
Return the lap duration when stopping the `Stopwatch`, which will be the duration since the last start.
If the stopwatch is not started, then the duration will be zero.
Use case - using a stopwatch to perform multiple duration timings, and then fetch the total elapsed time at the end (I can't see this is possible now, please direct me if I've just overlooked it though).
**Note:** CI failure does not seem related to my changes, as above though let me know if I missed something.
=> Stopwatch Lap Duration

.github/workflows/coding-style.yml, .github/workflows/psalm.yml, .github/workflows/tests.yml, .gitignore, README.md, src/DefaultClock.php, tests/DefaultClockTest.php
Closes https://github.com/brick/date-time/issues/91
=> Add `DefaultClock::travelBy(Duration)`, add `travelTo` to replace `travel`

src/LocalDate.php, src/Quarter.php, tests/LocalDateTest.php, tests/QuarterTest.php
Implementation suggestion for: #117 
I was very unsure about the actual implementation (lol). Would you add ceilXyz() to class Math?
I was unsure about adding more bells and whistles (especially to the Quarter enum?). 
Figured a serialized value of integer might be okay?
Let me know whats missing.
=> Add getQuarter() to LocalDate fixes #117
